In [2]:
import numpy as np

python_list = [1,2,3,4,5]

print('Type:', type (python_list))

print(python_list) 

two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]

print(two_dimensional_list)  

numpy_array_from_list = np.array(python_list)
print(type (numpy_array_from_list))
print(numpy_array_from_list) 

Type: <class 'list'>
[1, 2, 3, 4, 5]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'numpy.ndarray'>
[1 2 3 4 5]


In [3]:
two_dimensional_list = [[0,1,2], [3,4,5], [6,7,8]]
numpy_two_dimensional_list = np.array(two_dimensional_list)
print(type (numpy_two_dimensional_list))
print(numpy_two_dimensional_list)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
nums = np.array([1, 2, 3, 4, 5])
print(nums)
print('shape of nums: ', nums.shape)
numpy_two_dimensional_list = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(numpy_two_dimensional_list)
print('shape of numpy_two_dimensional_list: ', numpy_two_dimensional_list.shape)
three_by_four_array = np.array([[0, 1, 2, 3],
    [4,5,6,7],
    [8,9,10,11]])
print(three_by_four_array)
print('shape of three_by_four_array: ', three_by_four_array.shape)


[1 2 3 4 5]
shape of nums:  (5,)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
shape of numpy_two_dimensional_list:  (3, 3)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape of three_by_four_array:  (3, 4)


In [7]:
#heck data type
numpy_int_arr = np.array([1,2,3,4])
numpy_float_arr = np.array([1.1, 2.0,3.2])
numpy_bool_arr = np.array([-3, -2, 0, 1,2,3], dtype='bool')

print(numpy_int_arr.dtype)
print(numpy_float_arr.dtype)
print(numpy_bool_arr.dtype)

int64
float64
bool


In [ ]:
# change data type
numpy_int_arr = np.array([1,2,3,4], dtype='float')
print(numpy_int_arr)



[1. 2. 3. 4.]


In [9]:
#2D Array
two_dimension_array = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(type (two_dimension_array))
print(two_dimension_array)
print('Shape: ', two_dimension_array.shape)
print('Size:', two_dimension_array.size)
print('Data type:', two_dimension_array.dtype)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Size: 9
Data type: int64


In [12]:
# 2D Array
two_dimension_array = np.array([[1,2,3],[4,5,6], [7,8,9]])
first_row = two_dimension_array[0]
second_row = two_dimension_array[1]
third_row = two_dimension_array[2]
print('First row:', first_row)
print('Second row:', second_row)
print('Third row: ', third_row)
two_dimension_array[::]# reverse

First row: [1 2 3]
Second row: [4 5 6]
Third row:  [7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#generating random numbers
random_array = np.random.rand(3,4)
print(random_array)

[[0.2069935  0.69508281 0.28062064 0.0995368 ]
 [0.46674907 0.50279744 0.25460102 0.74934117]
 [0.56106371 0.68407182 0.54383444 0.43602632]]


In [16]:
integers = np.random.randint(0, 10, size=(3,4))
print(integers)


[[3 7 2 5]
 [2 4 6 3]
 [4 6 2 5]]


In [18]:
Matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(Matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
#numpy arthimetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('Addition: ', a + b)
print('Subtraction: ', a - b)
print('Multiplication: ', a * b)
print('Division: ', a / b)



Addition:  [5 7 9]
Subtraction:  [-3 -3 -3]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]


In [20]:
#matrix Arthimetic operations
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print('Addition: \n', A + B)
print('Subtraction: \n', A - B)
print('Element-wise Multiplication: \n', A * B)
print('Element-wise Division: \n', A / B)

Addition: 
 [[ 6  8]
 [10 12]]
Subtraction: 
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication: 
 [[ 5 12]
 [21 32]]
Element-wise Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


# <center>Pandas<center>

In [21]:
import pandas as pd

In [22]:
#creating pandas series
s = pd.Series([1, 2, 3, 4, 5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [31]:
#when trying to get the hacker file it responses 404 error so I am using iris dataset which is available in sklearn library
from sklearn.datasets import load_iris
import pandas as pd

data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)

df.to_csv("iris.csv", index=False)
print("Head----------:\n",df.head())
print("Tail-----------: \n",df.tail())

Head----------:
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
Tail-----------: 
      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8


In [34]:
print("Columns: \n", df.columns)

Columns: 
 Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')


In [37]:
filter = df['sepal length (cm)'] > 5.0
filtered_data = df[filter]
print("Filtered Data: \n", filtered_data)

Filtered Data: 
      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
5                  5.4               3.9                1.7               0.4
10                 5.4               3.7                1.5               0.2
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[118 rows x 4 columns]


In [38]:
df.shape

(150, 4)

# <center>Completed!!!</center>